import * as yup from 'yup';

export enum businessModelType {
  BRIDGE = 'BRIDGE',
  GROWTH = 'GROWTH',
  ENTERPRISE = 'ENTERPRISE',
  GROWTH_PLUS = 'GROWTH_PLUS',
}
export enum businessTypes {
  LLC = 'LLC',
  PLC = 'PLC',
  SOLETRADER = 'SOLETRADER',
  OPARTNRSHP = 'OPARTNRSHP',
  LPARTNRSHP = 'LPARTNRSHP',
  LLP = 'LLP',
  INDIVIDUAL = 'INDIVIDUAL',
  TRUST = 'TRUST',
  BENE_OWNER = 'BENE_OWNER',
} 
export enum countryCodes {
  AT = 'AT',
  BE = 'BE',
  BG = 'BG',
  CY = 'CY',
  CZ = 'CZ',
  DK = 'DK',
  EE = 'EE',
  FI = 'FI',
  FR = 'FR',
  DE = 'DE',
  GR = 'GR',
  HR = 'HR',
  HU = 'HU',
  IS = 'IS',
  IE = 'IE',
  IT = 'IT',
  LV = 'LV',
  LI = 'LI',
  LT = 'LT',
  LU = 'LU',
  MT = 'MT',
  NL = 'NL',
  NO = 'NO',
  PL = 'PL',
  PT = 'PT',
  RO = 'RO',
  SK = 'SK',
  SI = 'SI',
  ES = 'ES',
  SE = 'SE',
  GB = 'GB',
  MQ = 'MQ',
  YT = 'YT',
  GP = 'GP',
  GF = 'GF',
  RE = 'RE',
  MF = 'MF',
  GI = 'GI',
  GG = 'GG',
  IM = 'IM',
  JE = 'JE',
  MC = 'MC',
  CH = 'CH',
  AD = 'AD',
  SM = 'SM',
  VA = 'VA',
  AX = 'AX',
  PM = 'PM',
  BL = 'BL',
  AF = 'AF',
  AL = 'AL',
  DZ = 'DZ',
  AS = 'AS',
  AO = 'AO',
  AI = 'AI',
  AQ = 'AQ',
  AG = 'AG',
  AR = 'AR',
  AM = 'AM',
  AW = 'AW',
  AU = 'AU',
  AZ = 'AZ',
  BS = 'BS',
  BH = 'BH',
  BD = 'BD',
  BB = 'BB',
  BY = 'BY',
  BZ = 'BZ',
  BJ = 'BJ',
  BM = 'BM',
  BT = 'BT',
  BO = 'BO',
  BQ = 'BQ',
  BA = 'BA',
  BW = 'BW',
  BV = 'BV',
  BR = 'BR',
  IO = 'IO',
  VG = 'VG',
  BN = 'BN',
  BF = 'BF',
  BI = 'BI',
  KH = 'KH',
  CM = 'CM',
  CA = 'CA',
  CV = 'CV',
  KY = 'KY',
  CF = 'CF',
  TD = 'TD',
  CL = 'CL',
  CN = 'CN',
  CX = 'CX',
  CC = 'CC',
  CO = 'CO',
  KM = 'KM',
  CK = 'CK',
  CR = 'CR',
  CU = 'CU',
  CW = 'CW',
  CD = 'CD',
  DJ = 'DJ',
  DM = 'DM',
  DO = 'DO',
  TL = 'TL',
  EC = 'EC',
  EG = 'EG',
  SV = 'SV',
  GQ = 'GQ',
  ER = 'ER',
  SZ = 'SZ',
  ET = 'ET',
  FK = 'FK',
  FO = 'FO',
  FJ = 'FJ',
  PF = 'PF',
  TF = 'TF',
  GA = 'GA',
  GM = 'GM',
  GE = 'GE',
  GH = 'GH',
  GL = 'GL',
  GD = 'GD',
  GU = 'GU',
  GT = 'GT',
  GN = 'GN',
  GW = 'GW',
  GY = 'GY',
  HT = 'HT',
  HM = 'HM',
  HN = 'HN',
  HK = 'HK',
  IN = 'IN',
  ID = 'ID',
  IR = 'IR',
  IQ = 'IQ',
  IL = 'IL',
  CI = 'CI',
  JM = 'JM',
  JP = 'JP',
  JO = 'JO',
  KZ = 'KZ',
  KE = 'KE',
  KI = 'KI',
  XK = 'XK',
  KW = 'KW',
  KG = 'KG',
  LA = 'LA',
  LB = 'LB',
  LS = 'LS',
  LR = 'LR',
  LY = 'LY',
  MO = 'MO',
  MG = 'MG',
  MW = 'MW',
  MY = 'MY',
  MV = 'MV',
  ML = 'ML',
  MH = 'MH',
  MR = 'MR',
  MU = 'MU',
  MX = 'MX',
  FM = 'FM',
  MD = 'MD',
  MN = 'MN',
  ME = 'ME',
  MS = 'MS',
  MA = 'MA',
  MZ = 'MZ',
  MM = 'MM',
  NA = 'NA',
  NR = 'NR',
  NP = 'NP',
  AN = 'AN',
  NC = 'NC',
  NZ = 'NZ',
  NI = 'NI',
  NE = 'NE',
  NG = 'NG',
  NU = 'NU',
  NF = 'NF',
  KP = 'KP',
  MK = 'MK',
  MP = 'MP',
  OM = 'OM',
  PK = 'PK',
  PW = 'PW',
  PS = 'PS',
  PA = 'PA',
  PG = 'PG',
  PY = 'PY',
  PE = 'PE',
  PH = 'PH',
  PN = 'PN',
  PR = 'PR',
  QA = 'QA',
  CG = 'CG',
  RU = 'RU',
  RW = 'RW',
  SH = 'SH',
  KN = 'KN',
  LC = 'LC',
  VC = 'VC',
  WS = 'WS',
  ST = 'ST',
  SA = 'SA',
  SN = 'SN',
  RS = 'RS',
  SC = 'SC',
  SL = 'SL',
  SG = 'SG',
  SX = 'SX',
  SB = 'SB',
  SO = 'SO',
  ZA = 'ZA',
  KR = 'KR',
  GS = 'GS',
  SS = 'SS',
  LK = 'LK',
  SD = 'SD',
  SR = 'SR',
  SY = 'SY',
  SJ = 'SJ',
  TW = 'TW',
  TJ = 'TJ',
  TZ = 'TZ',
  TH = 'TH',
  TG = 'TG',
  TK = 'TK',
  TO = 'TO',
  TT = 'TT',
  TN = 'TN',
  TR = 'TR',
  TM = 'TM',
  TC = 'TC',
  TV = 'TV',
  UG = 'UG',
  UA = 'UA',
  AE = 'AE',
  UM = 'UM',
  US = 'US',
  UY = 'UY',
  UZ = 'UZ',
  VU = 'VU',
  VE = 'VE',
  VN = 'VN',
  VI = 'VI',
  WF = 'WF',
  EH = 'EH',
  YE = 'YE',
  ZM = 'ZM',
  ZW = 'ZW',
}
export enum legalEntityTypes { 
  IE = 'IE',
  GB = 'GB',
  NL = 'NL',
}
export enum personTypes {
  DIRECTOR = 'DIRECTOR',
  PARTNER = 'PARTNER',
  CSECRETARY = 'CSECRETARY',
  SOLETRADER = 'SOLETRADER',
  BENE_OWNER = 'BENE_OWNER',
  C_INTEREST = 'C_INTEREST',
  INDIVIDUAL = 'INDIVIDUAL',
  PCM_INDIVIDUAL = 'PCM_INDIVIDUAL',
  SIGNATORY = 'SIGNATORY',
  TRUST_SETTLOR = 'TRUST_SETTLOR',
  TRUST_BENEFICIARY = 'TRUST_BENEFICIARY',
  TRUST_TRUSTEE = 'TRUST_TRUSTEE',
} 

const addressSchema = yup.object().shape({
  line1: yup.string().required('Line 1 is required'),
  line2: yup.string(),
  line3: yup.string(),
  line4: yup.string(),
  postTown: yup.string().required('Post town is required'),
  postCode: yup.string().required('Post code is required'),
  country: yup.string().required('Country is required').oneOf(Object.values(countryCodes)),
});

const aliasSchema = yup.object().shape({
  title: yup.string(),
  firstName: yup.string().required('First name is required'),
  middleNames: yup.string(),
  lastName: yup.string().required('Last name is required'),
  dateChanged: yup.string(),
  reasonForChange: yup.string(),
});

const personDetailsSchema = yup.object().shape({
  id: yup.string().required('ID is required'),
  title: yup.string().required('Title is required'),
  firstName: yup.string().required('First name is required'),
  middleNames: yup.string(),
  lastName: yup.string().required('Last name is required'),
  dateOfBirth: yup.string().required('Date of birth is required'),
  countryOfBirth: yup.string().required('Country of birth is required').oneOf(Object.values(countryCodes)),
  email: yup.string().email(),
  phone: yup.string(),
  type: yup.string().required('Person type is required').oneOf(Object.values(personTypes)),
  ownership: yup.number().required('Ownership percentage is required'),
  cardHolder: yup.boolean(),
  accountPermission: yup.string().required('Account permission is required'),
  homeAddresses: yup.array().of(addressSchema).required('At least one home address is required'),
  alias: yup.array().of(aliasSchema),
});

const accountDetailsSchema = yup.object().shape({
  id: yup.string(),
  expectedMonthlySpend: yup.number(),
  accountName: yup.string(),
  accountCurrency: yup.string(),
});

const businessDetailsSchema = yup.object().shape({
  name: yup.string().required('Business name is required'),
  tradingAs: yup.string(),
  businessDescription: yup.string(),
  type: yup.string().required('Business type is required').oneOf(Object.values(businessTypes)),
  country: yup.string().required('Country is required').oneOf(Object.values(countryCodes)),
  businessStart: yup.string(),
  webLink: yup.string(),
  companyRegNumber: yup.string(),
  industryCode: yup.string(),
  VATNumber: yup.string(),
  legalEntity: yup.string().oneOf(Object.values(legalEntityTypes)),
  taxIdentifier: yup.string(),
  registeredAddress: addressSchema,
  tradingAddress: addressSchema,
});

export const editObjectTypeSchema = yup.object().shape({
  businessModel: yup.string().oneOf(Object.values(businessModelType), 'Business model is required'),
  businessDetails: businessDetailsSchema.required(),
  associates: yup.array().of(personDetailsSchema).required('At least one associate is required'),
  accounts: yup.array().of(accountDetailsSchema).required('At least one account is required'),
});

